# Generated by Django 5.2.10 on 2026-01-26 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Danmu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    models.BigIntegerField(db_index=True, verbose_name="关联视频CID"),
                ),
                (
                    "video_time",
                    models.FloatField(default=0, verbose_name="视频内出现时间"),
                ),
                ("content", models.TextField(verbose_name="弹幕内容")),
                (
                    "send_time",
                    models.DateTimeField(null=True, verbose_name="真实发送时间"),
                ),
                (
                    "user_hash",
                    models.CharField(
                        max_length=20, null=True, verbose_name="发送者Hash值"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(default=0.5, verbose_name="情感得分"),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        default="neutral", max_length=10, verbose_name="情感分类"
                    ),
                ),
            ],
            options={
                "db_table": "danmus",
                "ordering": ["-send_time"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "bvid",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="视频BV号",
                    ),
                ),
                ("aid", models.BigIntegerField(unique=True, verbose_name="视频AV号")),
                ("cid", models.BigIntegerField(null=True, verbose_name="弹幕ID")),
                (
                    "title",
                    models.CharField(
                        max_length=255, null=True, verbose_name="视频标题"
                    ),
                ),
                ("pubdate", models.DateTimeField(null=True, verbose_name="发布日期")),
            ],
            options={
                "db_table": "videos",
                "ordering": ["-pubdate"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "rpid",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="评论ID"
                    ),
                ),
                ("mid", models.BigIntegerField(verbose_name="用户UID")),
                (
                    "uname",
                    models.CharField(max_length=100, null=True, verbose_name="用户名"),
                ),
                ("message", models.TextField(verbose_name="评论正文")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "location",
                    models.CharField(max_length=50, null=True, verbose_name="IP属地"),
                ),
                ("ctime", models.DateTimeField(null=True, verbose_name="发布时间")),
                ("vip_type", models.IntegerField(default=0, verbose_name="会员类型")),
                (
                    "vip_label",
                    models.CharField(max_length=50, null=True, verbose_name="会员标签"),
                ),
                ("user_level", models.IntegerField(default=0, verbose_name="用户等级")),
                (
                    "parent_rpid",
                    models.BigIntegerField(default=0, verbose_name="父评论ID"),
                ),
                (
                    "sentiment_score",
                    models.FloatField(default=0.5, verbose_name="情感得分"),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        default="neutral", max_length=10, verbose_name="情感分类"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="analysis.video",
                        verbose_name="视频",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["-ctime"],
            },
        ),
    ]
