# Generated by Django 5.2.10 on 2026-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="duplicate_group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="重复组ID"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_duplicate",
            field=models.BooleanField(default=False, verbose_name="是否重复"),
        ),
        migrations.AddField(
            model_name="comment",
            name="quality_score",
            field=models.FloatField(default=0.5, verbose_name="质量评分"),
        ),
        migrations.AddField(
            model_name="danmu",
            name="duplicate_group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="重复组ID"
            ),
        ),
        migrations.AddField(
            model_name="danmu",
            name="is_duplicate",
            field=models.BooleanField(default=False, verbose_name="是否重复"),
        ),
        migrations.AddField(
            model_name="danmu",
            name="quality_score",
            field=models.FloatField(default=0.5, verbose_name="质量评分"),
        ),
    ]
