# Generated by Django 5.2.10 on 2026-01-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_comment_duplicate_group_comment_is_duplicate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(default=0, verbose_name="回复数/子评论数"),
        ),
    ]
