# Generated by Django 5.2.10 on 2026-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_comment_reply_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_length",
                    models.IntegerField(default=1, verbose_name="最小文本长度"),
                ),
                (
                    "max_length",
                    models.IntegerField(default=500, verbose_name="最大文本长度"),
                ),
                (
                    "min_chinese_ratio",
                    models.FloatField(default=0.15, verbose_name="最小中文占比"),
                ),
                (
                    "min_quality_score",
                    models.FloatField(default=0.2, verbose_name="最小质量评分"),
                ),
                (
                    "dedup_method",
                    models.CharField(
                        default="exact", max_length=20, verbose_name="去重方法"
                    ),
                ),
                (
                    "fuzzy_threshold",
                    models.FloatField(default=0.85, verbose_name="模糊去重阈值"),
                ),
                (
                    "embedding_threshold",
                    models.FloatField(default=0.85, verbose_name="语义去重阈值"),
                ),
                (
                    "max_char_repeat",
                    models.IntegerField(default=10, verbose_name="单字符最大重复"),
                ),
                (
                    "min_unique_ratio",
                    models.FloatField(default=0.2, verbose_name="最小字符多样性"),
                ),
                (
                    "min_unique_check_length",
                    models.IntegerField(default=15, verbose_name="多样性检查长度"),
                ),
                (
                    "high_like_threshold",
                    models.IntegerField(default=50, verbose_name="高赞阈值"),
                ),
                (
                    "high_reply_threshold",
                    models.IntegerField(default=10, verbose_name="热门讨论阈值"),
                ),
                (
                    "combined_like_threshold",
                    models.IntegerField(default=20, verbose_name="综合热度-点赞"),
                ),
                (
                    "combined_reply_threshold",
                    models.IntegerField(default=5, verbose_name="综合热度-回复"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
                "db_table": "user_config",
            },
        ),
        migrations.AlterField(
            model_name="danmu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
