# Generated by Django 5.2.10 on 2026-01-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_userconfig_alter_danmu_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconfig",
            name="background_color",
            field=models.CharField(
                default="#1a1a2e", max_length=7, verbose_name="背景颜色"
            ),
        ),
        migrations.AddField(
            model_name="userconfig",
            name="opacity",
            field=models.FloatField(default=0.95, verbose_name="透明度"),
        ),
    ]
