# Generated by Django 5.2.10 on 2026-01-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_emailverificationcode_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_color",
            field=models.CharField(
                default="#1a1a2e", max_length=7, verbose_name="背景颜色"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="combined_like_threshold",
            field=models.IntegerField(default=20, verbose_name="综合热度-点赞"),
        ),
        migrations.AddField(
            model_name="user",
            name="combined_reply_threshold",
            field=models.IntegerField(default=5, verbose_name="综合热度-回复"),
        ),
        migrations.AddField(
            model_name="user",
            name="dedup_method",
            field=models.CharField(
                default="exact", max_length=20, verbose_name="去重方法"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="embedding_threshold",
            field=models.FloatField(default=0.85, verbose_name="语义去重阈值"),
        ),
        migrations.AddField(
            model_name="user",
            name="fuzzy_threshold",
            field=models.FloatField(default=0.85, verbose_name="模糊去重阈值"),
        ),
        migrations.AddField(
            model_name="user",
            name="high_like_threshold",
            field=models.IntegerField(default=50, verbose_name="高赞阈值"),
        ),
        migrations.AddField(
            model_name="user",
            name="high_reply_threshold",
            field=models.IntegerField(default=10, verbose_name="热门讨论阈值"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_char_repeat",
            field=models.IntegerField(default=10, verbose_name="单字符最大重复"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_length",
            field=models.IntegerField(default=500, verbose_name="最大文本长度"),
        ),
        migrations.AddField(
            model_name="user",
            name="min_chinese_ratio",
            field=models.FloatField(default=0.15, verbose_name="最小中文占比"),
        ),
        migrations.AddField(
            model_name="user",
            name="min_length",
            field=models.IntegerField(default=1, verbose_name="最小文本长度"),
        ),
        migrations.AddField(
            model_name="user",
            name="min_quality_score",
            field=models.FloatField(default=0.2, verbose_name="最小质量评分"),
        ),
        migrations.AddField(
            model_name="user",
            name="min_unique_check_length",
            field=models.IntegerField(default=15, verbose_name="多样性检查长度"),
        ),
        migrations.AddField(
            model_name="user",
            name="min_unique_ratio",
            field=models.FloatField(default=0.2, verbose_name="最小字符多样性"),
        ),
        migrations.AddField(
            model_name="user",
            name="opacity",
            field=models.FloatField(default=0.95, verbose_name="透明度"),
        ),
    ]
