# Generated by Django 5.2.10 on 2026-01-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0007_user_background_color_user_combined_like_threshold_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="raw_comment_count",
            field=models.IntegerField(default=0, verbose_name="原始爬取评论数"),
        ),
    ]
