# Generated by Django 5.2.10 on 2026-01-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_video_raw_comment_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_offset", models.FloatField(verbose_name="视频内时间偏移(秒)")),
                (
                    "sentiment_score",
                    models.FloatField(default=0.5, verbose_name="情感得分"),
                ),
                ("sentiment_label", models.CharField(default="neutral", max_length=10)),
                (
                    "text_transcript",
                    models.TextField(blank=True, null=True, verbose_name="ASR转录文本"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_sentiments",
                        to="analysis.video",
                    ),
                ),
            ],
            options={
                "db_table": "audio_sentiments",
                "ordering": ["time_offset"],
            },
        ),
    ]
