# Generated by Django 5.2.10 on 2026-02-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0009_add_audio_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosentiment",
            name="emotion_probs",
            field=models.JSONField(default=dict, verbose_name="各情感概率分布"),
        ),
        migrations.AddField(
            model_name="audiosentiment",
            name="segment_duration",
            field=models.FloatField(default=15, verbose_name="分段时长(秒)"),
        ),
    ]
