# Generated by Django 5.2.10 on 2026-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_audiosentiment_emotion_probs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='B站Access Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='bili_jct',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='B站BILI_JCT'),
        ),
        migrations.AddField(
            model_name='user',
            name='bilibili_mid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='B站用户ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后刷新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='B站Refresh Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='sessdata',
            field=models.TextField(blank=True, null=True, verbose_name='B站SESSDATA'),
        ),
        migrations.AddField(
            model_name='user',
            name='sessdata_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SESSDATA过期时间'),
        ),
    ]
