# Generated by Django 5.2.10 on 2026-02-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_user_access_token_user_bili_jct_user_bilibili_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mid',
            field=models.BigIntegerField(db_index=True, verbose_name='用户UID'),
        ),
    ]
