# Generated by Django 5.2.10 on 2026-02-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_user_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_id', models.CharField(max_length=50, verbose_name='字幕段ID')),
                ('time_offset', models.FloatField(verbose_name='视频内时间偏移(秒)')),
                ('duration', models.FloatField(default=0, verbose_name='字幕持续时长(秒)')),
                ('content', models.TextField(verbose_name='字幕内容')),
                ('sentiment_score', models.FloatField(default=0.5, verbose_name='情感得分')),
                ('sentiment_label', models.CharField(default='neutral', max_length=10)),
                ('emotion_probs', models.JSONField(default=dict, verbose_name='各情感概率分布')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_sentiments', to='analysis.video')),
            ],
            options={
                'db_table': 'subtitle_sentiments',
                'ordering': ['time_offset'],
            },
        ),
    ]
