# Generated by Django 5.2.10 on 2026-02-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_add_subtitle_sentiment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubtitleSentiment',
        ),
    ]
