# Generated by Django 5.2.10 on 2026-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_add_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='B站Access Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='B站Refresh Token'),
        ),
    ]
