# Generated by Django on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_add_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.BigIntegerField(default=0, verbose_name='播放量'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='video',
            name='coin',
            field=models.BigIntegerField(default=0, verbose_name='投币数'),
        ),
        migrations.AddField(
            model_name='video',
            name='favorite',
            field=models.BigIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='video',
            name='share',
            field=models.BigIntegerField(default=0, verbose_name='分享数'),
        ),
    ]
