# Generated by Django 5.2.10 on 2026-02-22 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_video_stats_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now=True, verbose_name='最后分析时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='analysis.video', verbose_name='视频')),
            ],
            options={
                'db_table': 'user_video_history',
                'ordering': ['-analyzed_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
