# Generated by Django 5.2.10 on 2026-02-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_add_comment_danmu_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fused_positive', models.FloatField(default=0.33, verbose_name='融合正面概率')),
                ('fused_neutral', models.FloatField(default=0.33, verbose_name='融合中性概率')),
                ('fused_negative', models.FloatField(default=0.34, verbose_name='融合负面概率')),
                ('audio_weight', models.FloatField(default=0.35, verbose_name='音频权重')),
                ('text_weight', models.FloatField(default=0.35, verbose_name='文本权重')),
                ('danmu_weight', models.FloatField(default=0.3, verbose_name='弹幕权重')),
                ('audio_emotion', models.JSONField(default=dict, verbose_name='音频情感分布')),
                ('text_emotion', models.JSONField(default=dict, verbose_name='文本情感分布')),
                ('danmu_emotion', models.JSONField(default=dict, verbose_name='弹幕情感分布')),
                ('has_conflict', models.BooleanField(default=False, verbose_name='是否存在情感冲突')),
                ('conflict_details', models.JSONField(default=dict, verbose_name='冲突详情')),
                ('video_type', models.CharField(default='general', max_length=20, verbose_name='视频类型')),
                ('dominant_emotion', models.CharField(default='neutral', max_length=20, verbose_name='主导情感')),
                ('emotion_strength', models.FloatField(default=0.0, verbose_name='情感强度')),
                ('overall_score', models.FloatField(default=0.5, verbose_name='综合得分')),
                ('analyzed_at', models.DateTimeField(auto_now=True, verbose_name='分析时间')),
            ],
            options={
                'verbose_name': '多模态情感分析',
                'verbose_name_plural': '多模态情感分析',
                'db_table': 'multimodal_sentiments',
            },
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_video_sentiment_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_ctime_idx',
        ),
        migrations.RemoveIndex(
            model_name='danmu',
            name='danmu_cid_sentiment_idx',
        ),
        migrations.RemoveIndex(
            model_name='danmu',
            name='danmu_send_time_idx',
        ),
        migrations.AddField(
            model_name='multimodalsentiment',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_sentiment', to='analysis.video', verbose_name='视频'),
        ),
    ]
